language: perl
perl:
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
before_install:
    - "cpanm Test::More"
    - "cpanm Test::NoWarnings"
    - "cpanm Test::Exception"
    - "cpanm Devel::Cover::Report::Coveralls"
script:
  perl Makefile.PL && make test && cover -test -report coveralls
